artifacts_root: artifacts 


data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://drive.google.com/file/d/1NTX2p9xPAA7p6iKADt_1UiCXGry3YmJB/view?usp=sharing
 local_file_path: artifacts/data_ingestion/data.zip
 unzip_path: artifacts/data_ingestion

data_validation:
 root_dir: artifacts/data_validation
 unzip_path: artifacts/data_ingestion/winequalityN.csv
 STATUS_file: artifacts/data_validation/status.txt

data_transformation:
 root_dir: artifacts/data_transformation
 data_path: artifacts/data_ingestion/winequalityN.csv


model_trainer:
 root_dir: artifacts/model_trainer
 train_data_path: artifacts/data_transformation/train.csv
 test_data_path: artifacts/data_transformation/test.csv
 model_name: model.joblib

model_evaluation:
 root_dir: artifacts/model_evaluation
 test_data_path:  artifacts/data_transformation/test.csv
 model_path: artifacts/model_trainer/model.joblib
 metric_file_name: artifacts/model_evaluation/metrics.json
 